/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.it;

import org.junit.Assert;
import org.junit.Test;
import static org.junit.Assert.*;
import static edu.it.logicaspuras.Constantes.*;
import static edu.it.logicaspuras.JuegoPPT.jugar;

public class AppTest {
    @Test
    public void empate() {
        // Arrange - Arreglar los objetos que voy a probar
        // Act - Llamar al metodo
        // Assert - Evaluar resultado

        // Arrange
        Integer jugadorHumano = Piedra;
        Integer jugadorMaquina = Piedra;

        // Act
        Integer x = jugar(jugadorHumano, jugadorMaquina);

        // Assert
        Assert.assertEquals(x.longValue(), Empate);
    }
    @Test
    public void ganaJugador1() {
        // Act
        Integer resultado = jugar(Piedra, Tijera);

        // Assert
        Assert.assertEquals(resultado.longValue(), GanaJugador1);
    }
}
