/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.it;

import edu.it.logicaspuras.JuegoPPT;
import edu.it.polimorfismo.JugadorMaquina;
import edu.it.polimorfismo.JugadorPPT;
import edu.it.polimorfismo.JugadorPersona;
import edu.it.utiles.Utiles;

public class App {
    public static void main(String[] args) {
        JugadorPPT jugador1 = new JugadorPersona();
        JugadorPPT jugador2 = new JugadorPersona();

        for (boolean continuar=true; continuar; continuar = Utiles.quiereSeguirJugando()) {
            int resultado = JuegoPPT.jugar(
                    jugador1.obtenenerJugada(),
                    jugador2.obtenenerJugada());

            switch (resultado) {
                case 0:
                    System.out.println("Empate");
                    break;
                case 1:
                    System.out.println("Gano maquina 1");
                    break;
                case 2:
                    System.out.println("Gano maquina 2");
                    break;
            }
        }
    }
}
