/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.it;


import org.junit.jupiter.api.Test;

public class AppTest {
    @Test
    public void test1() {
        // Arrange - Arreglar los objetos que voy a probar
        // Act - Llamar al metodo
        // Assert - Evaluar resultado
    }
}
