/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.it;

import edu.it.vuelcoarchivo.Vuelcoarchivo;
import edu.it.vuelcoarchivo.VuelcoarchivoHTML;
import edu.it.vuelcoarchivo.VuelcoarchivoPlano;

public class App {
    public static void main(String[] args) throws Exception {
        Vuelcoarchivo vuelcoarchivo = (Vuelcoarchivo)
                Class.forName(args[0]).newInstance();
                new VuelcoarchivoHTML();

        vuelcoarchivo.volcar();
    }
}
