/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.it;

import com.github.javafaker.Faker;
import edu.it.model.Alumno;

import java.sql.*;
import java.util.*;

import static edu.it.utiles.Utiles.ver;

public class App {
    private static void crearMuchosAlumnos() {
        Faker fkr = Faker.instance();

        List<Alumno> alumnoList = new ArrayList<>();
        Map<String, Alumno> mapaAlumnos = new HashMap<>();
        Set<Alumno> alumnosSet = new HashSet<>();

        String ultimoId = null;
        for (int x:new int[5]) {
            ultimoId = UUID.randomUUID().toString();
            Alumno alumno = new Alumno(
                    ultimoId,
                    fkr.address().firstName(),
                    fkr.address().lastName());

            alumnoList.add(alumno);
            mapaAlumnos.put(ultimoId, alumno);
            alumnosSet.add(alumno);
        }

        Alumno z = alumnoList.get(3);
        ver(z);
        alumnoList.remove(2);
        alumnoList.remove(z);

        ver(alumnoList.size());

        ver("Problema del map: ", "voy a ver al alumno: ", ultimoId);
        ver(mapaAlumnos.get(ultimoId));

        ver();
        ver();
        ver("Problema del set y los duplicados");
        Alumno al1 = new Alumno("465695", "Rodolfo","Esquerra");
        Alumno al2 = new Alumno("465695", "Rodolfo","Esquerra");
        alumnosSet.add(al1);
        alumnosSet.add(al2);

        for (Alumno x : alumnosSet) {
            ver(x);
        }

    }
    private static void problemaHashEquals() {
        Object o = new Alumno("1", "Jose","lopez");

        ver(o.toString());
        ver(o.getClass().toString());
        ver(o.hashCode());
        // problema del equals;

        Object al1 = new Alumno("465695", "Rodolfo","Esquerra");
        Object al2 = new Alumno("465694", "Rodolfo","Esquerra");

        if  (al1.equals(al2)) {
            ver("Son iguales");
            ver(al1.hashCode());
            ver(al2.hashCode());
        }
        else {
            ver("son diferentes");
            ver(al1.hashCode());
            ver(al2.hashCode());
        }
    }
    public static void main(String[] args) throws Exception {
        crearMuchosAlumnos();
    }
}
