/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.educacionit.ppt;

public class App {
    public String getGreeting() {
        return "Hello world. amigos";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
    }
}
